# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-pgz-jewelrush

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Jewel Rush Puzzle Game
Version:    0.7.0
Release:    1
Group:      Games/Action
License:    GPL v2
URL:        http://www.piggz.co.uk
Source0:    %{name}-%{version}.tar.bz2
Requires:   qt5-qtdeclarative-import-sensors
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(qdeclarative5-boostable)
BuildRequires:  pkgconfig(Qt5Svg)
BuildRequires:  desktop-file-utils
BuildRequires:  sailfishsilica-qt5

%description
A simple to learn, addictive, action packed puzzle game.  Simply match the colours together, then blow them up!
The more you score the harder it gets.

%if "%{?vendor}" == "chum"
PackageName: Jewel Rush
Type: desktop-application
DeveloperName: Adam Pigg
Categories:
 - Game
Custom:
  Repo: https://github.com/piggz/jewelrush
Icon: https://raw.githubusercontent.com/piggz/galaxy-attack-hd/master/galaxy-attack-128.png
Screenshots:
 - https://raw.githubusercontent.com/piggz/jewelrush/main/media/screenshot_main.jpg
 - https://raw.githubusercontent.com/piggz/jewelrush/main/media/screenshot_help.jpg
 - https://raw.githubusercontent.com/piggz/jewelrush/main/media/screenshot_game.jpg
Url:
  Homepage: https://github.com/piggz/jewelrush
  Help: https://github.com/piggz/jewelrush/discussions
  Bugtracker: https://github.com/piggz/jewelrush/issues
  Donation: https://www.paypal.me/piggz
%endif

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
# >> files
# << files
